services:
- type: web
  name: todo_app
  env: python
  plan: starter
  buildCommand: ./build.sh
  startCommand: gunicorn todo_app.wsgi:application
  autoDeploy: false
  envVars:
    - key: WEB_CONCURRENCY
      value: 4
    - key: DATABASE_URL
      fromDatabase:
        name: djartaux
        property: connectionString
    - key: DJANGO_SECRET_KEY
      generateValue: true
    - key: DJANGO_ADMIN_URL
      generateValue: true
    - key: DJANGO_SETTINGS_MODULE
      value: config.settings.production

databases:
- name: djartaux
  databaseName: djartaux
  user: djartaux_user